### ISSUE TITLE
Using the templates on this repo for my project

### ISSUE THREAD

**Issue by hojoung97** [PurpleBooth/a-good-readme-template#4]
Am I allowed to use most of the contents without much modification?
Should I include citations/reference ti the source?
I am fairly new to open source community and just worried about getting in trouble for inappropriate use of others' work.

I am currently looking into using the templates for CONTRIBUTING.md and CODE_OF_CONDUCT.md.

**Comment by PurpleBooth** [comment]
The main text is [CC0](https://creativecommons.org/share-your-work/public-domain/cc0/) (README.md, CONTRIBUTING.md). You're not required to include citations unless you want to.

CODE_OF_CONDUCT is taken from the Contributor Covenant, they license it under "Creative Commons Attribution 4.0" which means you are required to link back them.

**Comment by hojoung97** [comment]
Thanks!
